
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aaxmbdmzsyfgnzielkir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFheG1iZG16c3lmZ256aWVsa2lyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4OTQ1OTYsImV4cCI6MjA2MzQ3MDU5Nn0.wK38wo4DWuvpoQrdlJNwwTMUnq_dVo_qVH5dwRhn2D8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Enable realtime subscriptions for relevant tables
supabase.channel('public:bubbles')
  .on('postgres_changes', { event: '*', schema: 'public', table: 'bubbles' }, () => {})
  .subscribe();

supabase.channel('public:reflects')
  .on('postgres_changes', { event: '*', schema: 'public', table: 'reflects' }, () => {})
  .subscribe();
